# Generated by Django 5.0.3 on 2025-04-30 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contact_user_household_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Notes',
            new_name='notes',
        ),
    ]
